name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: '1.22.3'
      
    - name: Build
      run: CGO_ENABLED=0 go build -o chat-server

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
        chmod 600 ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/google_compute_engine.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Copy Binary to VM
      run: |
        gcloud compute scp --recurse ./chat-server chat-server:~/chat-server --zone=${{ secrets.ZONE }} --ssh-key-file ~/.ssh/google_compute_engine

    - name: Copy Service File to VM
      run: |
        gcloud compute scp --recurse ./scripts/openssl.sh chat-server:~/openssl.sh --zone=${{ secrets.ZONE }} --ssh-key-file ~/.ssh/google_compute_engine

    - name: Set File Permissions on VM
      run: |
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command="chmod +x chat-server" --ssh-key-file ~/.ssh/google_compute_engine
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command="chmod +x openssl.sh" --ssh-key-file ~/.ssh/google_compute_engine

    - name: Run Openssl Script
      run: |
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command="chmod +x openssl.sh && ./openssl.sh" --ssh-key-file ~/.ssh/google_compute_engine
    
    - name: Set File Permissions for Service File
      run: |
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command="sudo chmod 644 key.pem && sudo chmod 644 cert.pem" --ssh-key-file ~/.ssh/google_compute_engine

    - name: Restart Service
      run: |
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command="sudo systemctl restart chat-server" --ssh-key-file ~/.ssh/google_compute_engine
