name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'
      
    - name: Build
      run: go build -o chat-server

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GCP
      run: |
        gcloud compute scp ./chat-server chat-server:~/chat-server --zone=europe-west10-a
        gcloud compute ssh chat-server --zone=europe-west10-a --command 'sudo systemctl restart chat-server'
