name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'
      
    - name: Build
      run: go build -o chat-server

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Copy the binary to the VM and restart the service
      run: |
        gcloud compute scp ./chat-server chat-server:~/chat-server --zone=${{ secrets.ZONE }}
        gcloud compute ssh chat-server --zone=${{ secrets.ZONE }} --command 'sudo systemctl restart chat-server'
      shell: /usr/bin/bash -e
      env:
        GOROOT: /opt/hostedtoolcache/go/1.17.0/x64
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_GHA_CREDS_PATH: ${{ secrets.GOOGLE_CREDENTIALS }}
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT }}
        CLOUDSDK_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT }}
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
        CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.1
